services: # Описание микросервисов (контейнеров)
  joke-app: # Имя контейнера (по умолчанию добавится -1)
    image: api:v1 # Базовый образ для контейнера (если такого нет, соберется из докерфайла)
    shm_size: 2g
    build: # Инструкции для сборки образа, если он не найден
      context: . # Контекст сборки (текущая директория)
      dockerfile: Dockerfile # Имя Dockerfile
    volumes: # Тома для монтирования
      - ./:/usr/workspace
      - /dev/shm:/dev/shm # Монтируем разделяемую память хоста
    command: /bin/sh -c "STAGE=$$STAGE pytest -o log_cli=true -m=$$SUITE --alluredir=report" # Команда для выполнения в контейнере
    environment: # Переменные окружения
      STAGE: ${STAGE:-dev}
      SUITE: ${SUITE:-regression}
      THREADS: ${THREADS:-4}
    tty: true # Для цветного вывода логов