[pytest]
markers =
    smoke: Critical tests to verify core functionality.
    regression: Full regression test suite.
    sanity: Targeted checks for specific fixes or features.
    test: test
    profile: Profile page tests
    step

addopts =
    -sv